# Generated by Django 5.0.1 on 2024-01-11 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('bg_color', models.CharField(default='HASHffffff', max_length=21)),
                ('text_color', models.CharField(default='HASH000000', max_length=21)),
                ('bg_header_color', models.CharField(default='HASH000000', max_length=21)),
                ('title_color', models.CharField(default='HASHffffff', max_length=21)),
                ('all_classes', models.CharField(default='', max_length=255)),
                ('header_classes', models.CharField(default='', max_length=255)),
                ('box_classes', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(max_length=500)),
                ('priority', models.IntegerField(default=999)),
                ('date', models.DateField(auto_now=True)),
                ('complete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toDo.todocategory')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toDo.todolist')),
            ],
        ),
    ]
